# Generated by Django 4.2.8 on 2024-06-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecnoVerde', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'login',
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
